### ISSUE TITLE
Need a new favicon/logo

### ISSUE THREAD

**Issue by theapurvap** [theapurvap/syncrypto#5]
We need high quality images for the application as well as to submit to Google for Drive api integration.

**Comment by zuuritaly** [comment]
Hello @theapurvap  ,
I'm a graphic designer and I design logos for open source projects.

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by theapurvap** [comment]
Hi Zuur,

Appreciate the help! To answer your question, I'm thinking something flat. Take a look at the site: https://theapurvap.github.io/syncrypto

It would be nice to convey the same message as the cloud heart lock thing on the site itself. As for the colors, that shade of grey, red, and some yellow? What ever you think is best. We would need various sizes, all squares, for submitting to Google for obtaining a production version of the keys. How about 256x256? I can scale it after accordingly.

- Apurva
